# Site settings
title: "Amit Thawait"
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:title
url: "https://amit-thawait.github.io" # the base hostname & protocol for your site
twitter_username: Amit_Thawait
github_username:  amit-thawait
description: "My day to day learnings"
yaml gems: ['emoji_for_jekyll']
gem: [jekyll-admin]

# Build settings
markdown: kramdown
comments: True
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "posts" # an empty string here means all files in the project
    values:
      layout: post
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: my_tags
    values:
      layout: blog_by_tag

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
      output: true
      permalink: /blog/tag/:name/