# Site settings
title: "Priti Biyani"
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:title
url: "http://pritibiyani.github.io" # the base hostname & protocol for your site
twitter_username: pritibiyani
github_username:  pritibiyani
yaml gems: ['emoji_for_jekyll']

# Build settings
markdown: kramdown
comments: True
highlighter: pygments
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "posts" # an empty string here means all files in the project
    values:
      layout: post