# Site settings
title: "Priti Biyani"
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:day/:title
url: "http://pritibiyani.github.io" # the base hostname & protocol for your site
twitter_username: pritibiyani
github_username:  pritibiyani

# Build settings
markdown: kramdown
comments: True
highlighter: pygments
