# Site settings
title: "Priti Biyani"
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:title
url: "http://pritibiyani.github.io" # the base hostname & protocol for your site
twitter_username: pritibiyani
github_username:  pritibiyani
redirects: yes

# Build settings
markdown: kramdown
comments: True
highlighter: pygments

sharing :
 provider : all
 twitter :
   size :
   via :
   count :
 facebook :
   appid : 205602882797935
   layout : button_count
   font :
   faces : false
   width : 90
 googleplus :
   size : medium
   width :
   annotation : bubble
 linkedin :
   counter : right

defaults:
  -
    scope:
      path: "posts" # an empty string here means all files in the project
    values:
      layout: post